version: 1.0.0+{build}

environment:
  matrix:
    - PHP_VERSION: 7.0
      VC_VERSION: 14
      BUILD_TYPE: Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013

    - PHP_VERSION: 7.3
      VC_VERSION: 15
      BUILD_TYPE: Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

    - PHP_VERSION: 7.3
      VC_VERSION: 15
      BUILD_TYPE: nts-Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

    # Temporary disabled, because on Windows with php 8 PSR extension always crashes.
    # - PHP_VERSION: 8.0
    #   VC_VERSION: 16
    #   BUILD_TYPE: Win32
    #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

    # - PHP_VERSION: 8.0
    #   VC_VERSION: 16
    #   BUILD_TYPE: nts-Win32
    #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

  PHP_SDK_VERSION: 2.1.9
  PECL_PSR_VERSION: 0.6.1
  ZEPHIR_PARSER_VERSION: 1.3.5
  ZEPHIR_PARSER_RELEASE: 538
  ZEPHIR_VERSION: 0.11.8

matrix:
  fast_finish: true

cache:
  - 'C:\Downloads -> .appveyor.yml'

clone_depth: 1
clone_folder: C:\Projects\php-appveyor

platform:
  - x86
  - x64

branches:
  only:
    - master
    - development

init:
  - ps: $DebugPreference = "SilentlyContinue" # Continue

install:
  - ps: Import-Module .\php-appveyor.psm1

  - ps: InstallPhpSdk     $Env:PHP_SDK_VERSION $Env:VC_VERSION $Env:PLATFORM
  - ps: InstallPhp        $Env:PHP_VERSION $Env:BUILD_TYPE $Env:VC_VERSION $Env:PLATFORM
  - ps: InstallPhpDevPack $Env:PHP_VERSION $Env:BUILD_TYPE $Env:VC_VERSION $Env:PLATFORM

  - ps: TuneUpPhp -DefaultExtensions fileinfo
  - ps: InstallComposer
  - ps: InstallZephir -Version $Env:ZEPHIR_VERSION

before_build:
  - ps: >-
      InstallPeclExtension `
        -Name       psr `
        -Version    $Env:PECL_PSR_VERSION `
        -PhpVersion $Env:PHP_VERSION `
        -BuildType  $Env:BUILD_TYPE `
        -VC         $Env:VC_VERSION `
        -Platform   $Env:PLATFORM

  - ps: >-
      InstallZephirParser `
        -Version    $Env:ZEPHIR_PARSER_VERSION `
        -BuildId    $Env:ZEPHIR_PARSER_RELEASE `
        -PhpVersion $Env:PHP_VERSION `
        -BuildType  $Env:BUILD_TYPE `
        -VC         $Env:VC_VERSION `
        -Platform   $Env:PLATFORM

  - ps: EnablePhpExtension -Name psr
  - ps: EnablePhpExtension -Name zephir_parser -PrintableName "Zephir Parser"

build_script:
  - C:\php\php.exe --ri psr
  - C:\php\php.exe --ri "Zephir Parser"

test_script:
  - ps: .\composer --version
  - ps: .\zephir --version

after_test:
  - ps: >-
      PrepareReleasePackage `
        -PhpVersion     $Env:PHP_VERSION `
        -BuildType      $Env:BUILD_TYPE `
        -Platform       $Env:PLATFORM `
        -ZipballName    php-appveyor `
        -ReleaseFiles   LICENSE,README.md `
        -ConverMdToHtml $true

artifacts:
  - path: '.\php-appveyor.zip'
    type: zip
    name: php-appveyor

on_failure:
  - ps: >-
      Get-ChildItem -Path "C:\php\ext\"
